#!/usr/bin/env python3
"""Renders assets/social-preview.png — the image GitHub shows when the repo is
shared — from assets/social-preview.html.

macOS only, and it uses QuickLook rather than a browser, which constrains the
source page in three ways worth knowing before editing it:

  * QuickLook lays the page out in a **1024 px viewport** and scales the
    thumbnail up to whatever -s asks for. The page is therefore authored at
    1024, not at the final 1280.
  * It runs **no JavaScript**. The meter bars are static markup, generated by
    hand rather than in a script tag.
  * It loads **no web fonts**. The system face is the design, not a fallback.

It also only ever emits a square, so the page puts a full-bleed card behind
vertically centred content and this crops the middle — which lands on the
content however the renderer chooses to lay the page out.

    python3 scripts/render-banner.py
"""

import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SOURCE = os.path.join(ROOT, "assets", "social-preview.html")
OUTPUT = os.path.join(ROOT, "assets", "social-preview.png")

# GitHub's social preview is 2:1 and shown at 1280x640.
WIDTH, HEIGHT = 1280, 640


def main():
    for tool in ("qlmanage", "sips"):
        if shutil.which(tool) is None:
            sys.exit(f"error: {tool} not found — this script needs macOS")

    with tempfile.TemporaryDirectory() as work:
        subprocess.run(
            ["qlmanage", "-t", "-s", str(WIDTH), "-o", work, SOURCE],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        square = os.path.join(work, os.path.basename(SOURCE) + ".png")
        if not os.path.exists(square):
            sys.exit("error: QuickLook produced no thumbnail")

        # sips crops from the centre, which is exactly what the page is built for.
        subprocess.run(
            ["sips", "-c", str(HEIGHT), str(WIDTH), square, "--out", OUTPUT],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

    size = os.path.getsize(OUTPUT)
    print(f"wrote {os.path.relpath(OUTPUT, ROOT)}  {WIDTH}x{HEIGHT}  {size // 1024} KB")
    if size > 1024 * 1024:
        print("warning: over GitHub's 1 MB limit for a social preview", file=sys.stderr)


if __name__ == "__main__":
    main()
